-- Migration 006: Add NOTIFICACIONES table and WhatsApp support
-- Date: 2026-08-04

-- NOTIFICACIONES table (was referenced in code but missing from schema)
CREATE TABLE IF NOT EXISTS NOTIFICACIONES (
    NOT_ID SERIAL PRIMARY KEY,
    EMP_ID INTEGER REFERENCES EMPRESAS(EMP_ID),
    NOT_TIPO TEXT,
    NOT_MENSAJE TEXT,
    NOT_ESTADO TEXT DEFAULT 'PENDIENTE',
    PED_ID INTEGER,
    NOT_CREATED TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS IDX_NOTIF_EMP ON NOTIFICACIONES(EMP_ID);
CREATE INDEX IF NOT EXISTS IDX_NOTIF_PED ON NOTIFICACIONES(PED_ID);