-- Migration 007: COD (Cash on Delivery) + Driver Settlements
-- Date: 2026-08-04

-- Add COD columns to PEDIDOS
ALTER TABLE PEDIDOS ADD COLUMN IF NOT EXISTS PED_MONEDA TEXT DEFAULT 'MXN';
ALTER TABLE PEDIDOS ADD COLUMN IF NOT EXISTS PED_TIPO_ENVIO TEXT DEFAULT 'ESTANDAR';
ALTER TABLE PEDIDOS ADD COLUMN IF NOT EXISTS PED_PAGO_ESTATUS TEXT DEFAULT 'PENDIENTE';
ALTER TABLE PEDIDOS ADD COLUMN IF NOT EXISTS PED_PAGO_FECHA TIMESTAMP;
ALTER TABLE PEDIDOS ADD COLUMN IF NOT EXISTS PED_CANTIDAD_COBRADA REAL DEFAULT 0;

-- Driver cash holdings
CREATE TABLE IF NOT EXISTS DRIVER_CASH_HOLDINGS (
    HOLDING_ID SERIAL PRIMARY KEY,
    EMP_ID INTEGER NOT NULL REFERENCES EMPRESAS(EMP_ID),
    CHO_ID INTEGER NOT NULL,
    PED_ID INTEGER NOT NULL REFERENCES PEDIDOS(PED_ID),
    CASH_MONTO REAL NOT NULL,
    CASH_MONEDA TEXT DEFAULT 'MXN',
    CASH_ESTADO TEXT DEFAULT 'HOLDING',
    CASH_FECHA_COBRO TIMESTAMP DEFAULT NOW(),
    CASH_FECHA_DEPOSITO TIMESTAMP,
    CASH_NOTAS TEXT,
    CASH_DEPOSITO_REF TEXT
);

CREATE INDEX IF NOT EXISTS IX_CASH_EMP ON DRIVER_CASH_HOLDINGS(EMP_ID);
CREATE INDEX IF NOT EXISTS IX_CASH_CHO ON DRIVER_CASH_HOLDINGS(CHO_ID);

-- Driver settlements
CREATE TABLE IF NOT EXISTS DRIVER_SETTLEMENTS (
    SETTLE_ID SERIAL PRIMARY KEY,
    EMP_ID INTEGER NOT NULL REFERENCES EMPRESAS(EMP_ID),
    CHO_ID INTEGER NOT NULL,
    SETTLE_FECHA_INICIO TIMESTAMP NOT NULL,
    SETTLE_FECHA_FIN TIMESTAMP NOT NULL,
    SETTLE_TOTAL_PEDIDOS INTEGER DEFAULT 0,
    SETTLE_TOTAL_COD REAL DEFAULT 0,
    SETTLE_TOTAL_COMISION REAL DEFAULT 0,
    SETTLE_TOTAL_A_DEPOSITAR REAL DEFAULT 0,
    SETTLE_DEPOSITADO REAL DEFAULT 0,
    SETTLE_FECHA_DEPOSITO TIMESTAMP,
    SETTLE_ESTATUS TEXT DEFAULT 'PENDIENTE',
    SETTLE_CREATED TIMESTAMP DEFAULT NOW(),
    SETTLE_NOTAS TEXT
);

CREATE INDEX IF NOT EXISTS IX_SETTLE_EMP ON DRIVER_SETTLEMENTS(EMP_ID);
CREATE INDEX IF NOT EXISTS IX_SETTLE_CHO ON DRIVER_SETTLEMENTS(CHO_ID);

-- Settlement line items
CREATE TABLE IF NOT EXISTS SETTLEMENT_LINE_ITEMS (
    SLI_ID SERIAL PRIMARY KEY,
    SETTLE_ID INTEGER NOT NULL REFERENCES DRIVER_SETTLEMENTS(SETTLE_ID),
    PED_ID INTEGER NOT NULL REFERENCES PEDIDOS(PED_ID),
    SLI_MONTO_ESPERADO REAL NOT NULL,
    SLI_MONTO_COBRADO REAL DEFAULT 0,
    SLI_DIFERENCIA REAL DEFAULT 0,
    SLI_ESTADO TEXT DEFAULT 'PENDIENTE'
);