-- ========================================
-- MIGRATION: Multi-Country Fiscal Tables
-- Run this on PostgreSQL (Supabase)
-- ========================================

-- Tabla de configuracion fiscal del tenant
CREATE TABLE IF NOT EXISTS TENANT_FISCAL_CONFIG (
    TFC_ID SERIAL PRIMARY KEY,
    EMP_ID INTEGER NOT NULL UNIQUE REFERENCES EMPRESAS(EMP_ID),
    TFC_COUNTRY_CODE TEXT NOT NULL DEFAULT 'MX',
    TFC_PROVIDER TEXT NOT NULL DEFAULT 'MEXICO',
    TFC_API_KEY TEXT,
    TFC_API_SECRET TEXT,
    TFC_BASE_URL TEXT,
    TFC_ENABLED TEXT DEFAULT 'N',
    TFC_TEST_MODE TEXT DEFAULT 'S',
    TFC_CUSTOM_CONFIG TEXT DEFAULT '{}',
    TFC_FECHA_REGISTRO TIMESTAMP DEFAULT NOW(),
    TFC_FECHA_ACTUALIZACION TIMESTAMP DEFAULT NOW()
);

-- Tabla de datos fiscales del tenant
CREATE TABLE IF NOT EXISTS TENANT_FISCAL_DATA (
    TFD_ID SERIAL PRIMARY KEY,
    EMP_ID INTEGER NOT NULL UNIQUE REFERENCES EMPRESAS(EMP_ID),
    TFD_RFC TEXT,
    TFD_RAZON_SOCIAL TEXT,
    TFD_REGIMEN_FISCAL TEXT,
    TFD_CODIGO_POSTAL TEXT,
    TFD_COLONIA TEXT,
    TFD_CALLE TEXT,
    TFD_NUMERO_EXTERIOR TEXT,
    TFD_MUNICIPIO TEXT,
    TFD_ESTADO TEXT,
    TFD_TELEFONO TEXT,
    TFD_EMAIL TEXT,
    TFD_CNPJ TEXT,
    TFD_IE TEXT,
    TFD_IM TEXT,
    TFD_CNAE TEXT,
    TFD_CODIGO_MUNICIPIO TEXT,
    TFD_NIT TEXT,
    TFD_CODIGO_DOC_IDENTIFICACION TEXT,
    TFD_NUMERO_DOC_IDENTIFICACION TEXT,
    TFD_CUIT TEXT,
    TFD_CONDICION_IVA TEXT,
    TFD_CONDICION_INGRESOS_BRUTOS TEXT,
    TFD_RUT TEXT,
    TFD_GIRO TEXT,
    TFD_COMUNA TEXT,
    TFD_CIUDAD TEXT,
    TFD_REGION TEXT,
    TFD_TIPO_PERSONA TEXT DEFAULT 'M',
    TFD_ESTATUS TEXT DEFAULT 'ACTIVO',
    TFD_FECHA_REGISTRO TIMESTAMP DEFAULT NOW(),
    TFD_FECHA_ACTUALIZACION TIMESTAMP DEFAULT NOW()
);

-- Tabla de documentos fiscales multi-pais
CREATE TABLE IF NOT EXISTS FISCAL_DOCUMENTS (
    FD_ID SERIAL PRIMARY KEY,
    EMP_ID INTEGER NOT NULL REFERENCES EMPRESAS(EMP_ID),
    FD_DOCUMENT_ID TEXT,
    FD_DOCUMENT_TYPE TEXT DEFAULT 'FACTURA',
    FD_COUNTRY_CODE TEXT NOT NULL,
    FD_UUID TEXT,
    FD_SERIE TEXT,
    FD_FOLIO TEXT,
    FD_NUMERO TEXT,
    FD_FECHA_EMISION TIMESTAMP DEFAULT NOW(),
    FD_FECHA_TIMBRADO TEXT,
    FD_MONEDA TEXT DEFAULT 'MXN',
    FD_SUBTOTAL REAL DEFAULT 0,
    FD_DESCUENTO REAL DEFAULT 0,
    FD_IMPUESTOS REAL DEFAULT 0,
    FD_TOTAL REAL DEFAULT 0,
    FD_RECEPTOR_TIPO_DOC TEXT,
    FD_RECEPTOR_NUM_DOC TEXT,
    FD_RECEPTOR_NOMBRE TEXT,
    FD_RECEPTOR_DIRECCION TEXT,
    FD_RECEPTOR_EMAIL TEXT,
    FD_PED_ID INTEGER,
    FD_XML_URL TEXT,
    FD_PDF_URL TEXT,
    FD_ESTATUS TEXT DEFAULT 'PENDIENTE',
    FD_MOTIVO_CANCELACION TEXT,
    FD_UUID_SUSTITUCION TEXT,
    FD_NOTAS TEXT,
    FD_FECHA_REGISTRO TIMESTAMP DEFAULT NOW()
);

-- Indices
CREATE INDEX IF NOT EXISTS IX_TFC_EMP ON TENANT_FISCAL_CONFIG(EMP_ID);
CREATE INDEX IF NOT EXISTS IX_TFC_COUNTRY ON TENANT_FISCAL_CONFIG(TFC_COUNTRY_CODE);
CREATE INDEX IF NOT EXISTS IX_TFD_EMP ON TENANT_FISCAL_DATA(EMP_ID);
CREATE INDEX IF NOT EXISTS IX_FD_EMP ON FISCAL_DOCUMENTS(EMP_ID);
CREATE INDEX IF NOT EXISTS IX_FD_COUNTRY ON FISCAL_DOCUMENTS(FD_COUNTRY_CODE);
CREATE INDEX IF NOT EXISTS IX_FD_ESTATUS ON FISCAL_DOCUMENTS(FD_ESTATUS);
CREATE INDEX IF NOT EXISTS IX_FD_FECHA ON FISCAL_DOCUMENTS(FD_FECHA_EMISION);

-- Tabla de metodos de pago por pais
CREATE TABLE IF NOT EXISTS PAYMENT_METHODS_COUNTRY (
    PMC_ID SERIAL PRIMARY KEY,
    PMC_COUNTRY_CODE TEXT NOT NULL,
    PMC_METHOD_CODE TEXT NOT NULL,
    PMC_METHOD_NAME TEXT NOT NULL,
    PMC_PROVIDER TEXT,
    PMC_CONFIG TEXT DEFAULT '{}',
    PMC_ACTIVO TEXT DEFAULT 'S',
    PMC_FECHA_REGISTRO TIMESTAMP DEFAULT NOW(),
    UNIQUE(PMC_COUNTRY_CODE, PMC_METHOD_CODE)
);

-- Datos iniciales de metodos de pago por pais
INSERT INTO PAYMENT_METHODS_COUNTRY (PMC_COUNTRY_CODE, PMC_METHOD_CODE, PMC_METHOD_NAME, PMC_PROVIDER) VALUES
-- Mexico
('MX', 'EFECTIVO', 'Efectivo', NULL),
('MX', 'TARJETA_CREDITO', 'Tarjeta de Credito', 'stripe'),
('MX', 'TARJETA_DEBITO', 'Tarjeta de Debito', 'stripe'),
('MX', 'TRANSFERENCIA', 'Transferencia Bancaria', NULL),
('MX', 'MERCADOPAGO', 'MercadoPago', 'mercadopago'),
('MX', 'OXXO', 'OXXO', 'stripe'),
-- Brasil
('BR', 'PIX', 'PIX', 'mercadopago'),
('BR', 'BOLETO', 'Boleto Bancario', 'mercadopago'),
('BR', 'CARTAO_CREDITO', 'Cartao de Credito', 'stripe'),
('BR', 'CARTAO_DEBITO', 'Cartao de Debito', 'stripe'),
('BR', 'TRANSFERENCIA', 'Transferencia Bancaria', NULL),
-- Colombia
('CO', 'PSE', 'PSE', 'mercadopago'),
('CO', 'NEQUI', 'Nequi', NULL),
('CO', 'DAVIPLATA', 'Daviplata', NULL),
('CO', 'TARJETA_CREDITO', 'Tarjeta de Credito', 'stripe'),
('CO', 'TARJETA_DEBITO', 'Tarjeta de Debito', 'stripe'),
('CO', 'EFECTIVO', 'Efectivo (Baloto, Efecty)', NULL),
('CO', 'BANCOLOMBIA', 'Bancolombia', NULL),
-- Argentina
('AR', 'MERCADOPAGO', 'MercadoPago', 'mercadopago'),
('AR', 'TARJETA_CREDITO', 'Tarjeta de Credito', 'stripe'),
('AR', 'TARJETA_DEBITO', 'Tarjeta de Debito', 'stripe'),
('AR', 'TRANSFERENCIA', 'Transferencia Bancaria', NULL),
('AR', 'EFECTIVO', 'Efectivo (Rapipago, Pago Facil)', NULL),
('AR', 'CRYPTO', 'Criptomonedas', NULL),
-- Chile
('CL', 'WEBPAY', 'Webpay', 'stripe'),
('CL', 'TARJETA_CREDITO', 'Tarjeta de Credito', 'stripe'),
('CL', 'TARJETA_DEBITO', 'Tarjeta de Debito', 'stripe'),
('CL', 'TRANSFERENCIA', 'Transferencia Bancaria', NULL),
('CL', 'EFECTIVO', 'Efectivo (Khipu)', NULL),
('CL', 'MERCADOPAGO', 'MercadoPago', 'mercadopago'),
-- Peru
('PE', 'YAPE', 'Yape', NULL),
('PE', 'PLIN', 'Plin', NULL),
('PE', 'TARJETA_CREDITO', 'Tarjeta de Credito', 'stripe'),
('PE', 'TARJETA_DEBITO', 'Tarjeta de Debito', 'stripe'),
('PE', 'TRANSFERENCIA', 'Transferencia Bancaria', NULL),
('PE', 'EFECTIVO', 'Efectivo', NULL),
-- Uruguay
('UY', 'MERCADOPAGO', 'MercadoPago', 'mercadopago'),
('UY', 'TARJETA_CREDITO', 'Tarjeta de Credito', 'stripe'),
('UY', 'TARJETA_DEBITO', 'Tarjeta de Debito', 'stripe'),
('UY', 'TRANSFERENCIA', 'Transferencia Bancaria', NULL),
('UY', 'EFECTIVO', 'Efectivo', NULL),
-- Ecuador
('EC', 'TARJETA_CREDITO', 'Tarjeta de Credito', 'stripe'),
('EC', 'TARJETA_DEBITO', 'Tarjeta de Debito', 'stripe'),
('EC', 'TRANSFERENCIA', 'Transferencia Bancaria', NULL),
('EC', 'EFECTIVO', 'Efectivo', NULL),
('EC', 'PICHINCHA', 'Pichincha', NULL)
ON CONFLICT (PMC_COUNTRY_CODE, PMC_METHOD_CODE) DO NOTHING;

-- Vista de metodos de pago por empresa
DROP VIEW IF EXISTS V_EMPRESA_PAYMENT_METHODS;
CREATE VIEW V_EMPRESA_PAYMENT_METHODS AS
SELECT
    e.EMP_ID,
    e.EMP_NOMBRE,
    tfc.TFC_COUNTRY_CODE,
    pmc.PMC_METHOD_CODE,
    pmc.PMC_METHOD_NAME,
    pmc.PMC_PROVIDER,
    pmc.PMC_ACTIVO
FROM EMPRESAS e
LEFT JOIN TENANT_FISCAL_CONFIG tfc ON e.EMP_ID = tfc.EMP_ID
LEFT JOIN PAYMENT_METHODS_COUNTRY pmc ON tfc.TFC_COUNTRY_CODE = pmc.PMC_COUNTRY_CODE
WHERE pmc.PMC_ACTIVO = 'S';
