"""
LAST MILE DELIVERY - SQLite Database Schema
Migracion desde AS/400 DB2/400 -> SQLite
Todas las tablas y vistas del sistema.
"""

import sqlite3
import os

DB_PATH = os.path.join(os.path.dirname(__file__), 'lastmile.db')


def get_db():
    """Get SQLite connection with WAL mode for concurrency."""
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    conn.execute("PRAGMA busy_timeout=5000")
    return conn


def init_db():
    """Create all tables and views in SQLite."""
    conn = get_db()
    c = conn.cursor()

    # ========================================
    # TABLAS BASE
    # ========================================

    c.execute("""CREATE TABLE IF NOT EXISTS EMPRESAS (
        EMP_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        EMP_NOMBRE TEXT NOT NULL,
        EMP_RFC TEXT,
        EMP_DIRECCION TEXT,
        EMP_TELEFONO TEXT,
        EMP_EMAIL TEXT,
        EMP_CONTACTO TEXT,
        EMP_FECHA_ALTA TEXT DEFAULT (datetime('now')),
        EMP_ESTATUS TEXT DEFAULT 'ACTIVA',
        EMP_PLAN TEXT DEFAULT 'STARTER',
        EMP_MAX_USUARIOS INTEGER DEFAULT 5,
        EMP_MAX_CHOFERES INTEGER DEFAULT 10,
        EMP_MAX_PEDIDOS_MES INTEGER DEFAULT 500
    )""")

    c.execute("""CREATE TABLE IF NOT EXISTS USUARIOS (
        USU_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        USU_EMP_ID INTEGER NOT NULL,
        USU_USUARIO TEXT NOT NULL,
        USU_PASS TEXT NOT NULL,
        USU_NOMBRE TEXT NOT NULL,
        USU_EMAIL TEXT,
        USU_TELEFONO TEXT,
        USU_ROL TEXT NOT NULL DEFAULT 'operacion',
        USU_ACTIVO TEXT DEFAULT 'S',
        USU_CREATED TEXT DEFAULT (datetime('now')),
        USU_UPDATED TEXT DEFAULT (datetime('now')),
        FOREIGN KEY (USU_EMP_ID) REFERENCES EMPRESAS(EMP_ID)
    )""")

    c.execute("CREATE INDEX IF NOT EXISTS IX_USU_USER ON USUARIOS(USU_USUARIO)")
    c.execute("CREATE INDEX IF NOT EXISTS IX_USU_EMP ON USUARIOS(USU_EMP_ID)")

    # ========================================
    # CHOFERES
    # ========================================
    c.execute("""CREATE TABLE IF NOT EXISTS CHOFERES (
        CHO_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        EMP_ID INTEGER NOT NULL,
        CHO_NOMBRE TEXT,
        CHO_APELLIDO TEXT,
        CHO_RFC TEXT,
        CHO_LICENCIA TEXT,
        CHO_TELEFONO TEXT,
        CHO_EMAIL TEXT,
        CHO_FECHA_ALTA TEXT,
        CHO_ESTATUS TEXT DEFAULT 'ACTIVO',
        CHO_TIPO TEXT DEFAULT 'PROPIO',
        CHO_SALARIO_BASE REAL DEFAULT 0,
        CHO_COMISION_PCT REAL DEFAULT 0,
        FOREIGN KEY (EMP_ID) REFERENCES EMPRESAS(EMP_ID)
    )""")

    # ========================================
    # VEHICULOS
    # ========================================
    c.execute("""CREATE TABLE IF NOT EXISTS VEHICULOS (
        VEH_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        EMP_ID INTEGER NOT NULL,
        VEH_UNIDAD TEXT,
        VEH_MARCA TEXT,
        VEH_MODELO TEXT,
        VEH_ANIO TEXT,
        VEH_PLACAS TEXT,
        VEH_COLOR TEXT,
        VEH_TIPO TEXT DEFAULT 'CAMIONETA',
        VEH_CAPACIDAD_KG REAL DEFAULT 0,
        VEH_CAPACIDAD_M3 REAL DEFAULT 0,
        VEH_ESTATUS TEXT DEFAULT 'DISPONIBLE',
        VEH_GPS_ACTIVO TEXT DEFAULT 'N',
        VEH_ULTIMA_VELOCIDAD REAL DEFAULT 0,
        FOREIGN KEY (EMP_ID) REFERENCES EMPRESAS(EMP_ID)
    )""")

    # ========================================
    # CLIENTES
    # ========================================
    c.execute("""CREATE TABLE IF NOT EXISTS CLIENTES_LM (
        CLI_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        EMP_ID INTEGER NOT NULL,
        CLI_RAZON_SOCIAL TEXT,
        CLI_RFC TEXT,
        CLI_CONTACTO TEXT,
        CLI_TELEFONO TEXT,
        CLI_EMAIL TEXT,
        CLI_DIRECCION TEXT,
        CLI_COLONIA TEXT,
        CLI_CIUDAD TEXT,
        CLI_ESTADO TEXT,
        CLI_CP TEXT,
        CLI_LATITUD REAL,
        CLI_LONGITUD REAL,
        CLI_ZONA TEXT,
        CLI_ESTATUS TEXT DEFAULT 'ACTIVO',
        CLI_FECHA_ALTA TEXT,
        CLI_TIPO_CLIENTE TEXT DEFAULT 'GENERAL',
        CLI_CREDITO REAL DEFAULT 0,
        CLI_SALDO REAL DEFAULT 0,
        FOREIGN KEY (EMP_ID) REFERENCES EMPRESAS(EMP_ID)
    )""")

    # ========================================
    # PEDIDOS
    # ========================================
    c.execute("""CREATE TABLE IF NOT EXISTS PEDIDOS (
        PED_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        EMP_ID INTEGER NOT NULL,
        PED_NUMERO TEXT,
        CLI_ID INTEGER,
        PED_CLIENTE_NOMBRE TEXT,
        PED_CLIENTE_TELEFONO TEXT,
        PED_CLIENTE_EMAIL TEXT,
        PED_ORIGEN_DIR TEXT,
        PED_ORIGEN_LAT REAL,
        PED_ORIGEN_LON REAL,
        PED_DESTINO_DIR TEXT,
        PED_DESTINO_COL TEXT,
        PED_DESTINO_CIUDAD TEXT,
        PED_DESTINO_ESTADO TEXT,
        PED_DESTINO_CP TEXT,
        PED_DESTINO_LAT REAL,
        PED_DESTINO_LON REAL,
        PED_DESCRIPCION TEXT,
        PED_REFERENCIA TEXT,
        PED_PESO_KG REAL DEFAULT 0,
        PED_VOLUMEN_M3 REAL DEFAULT 0,
        PED_BULTOS INTEGER DEFAULT 1,
        PED_VALOR_DECLARADO REAL DEFAULT 0,
        PED_COSTO_ENVIO REAL DEFAULT 0,
        PED_COSTO_TOTAL REAL DEFAULT 0,
        PED_FORMA_PAGO TEXT DEFAULT 'EFECTIVO',
        PED_ESTADO TEXT DEFAULT 'PENDIENTE',
        PED_PRIORIDAD TEXT DEFAULT 'NORMAL',
        PED_FECHA_PEDIDO TEXT DEFAULT (datetime('now')),
        PED_FECHA_RECOLECTA TEXT,
        PED_FECHA_ENTREGA_EST TEXT,
        PED_FECHA_ENTREGA_REAL TEXT,
        PED_INSTRUCCIONES TEXT,
        PED_NOTASINTERNAS TEXT,
        CHO_ID INTEGER,
        VEH_ID INTEGER,
        CHOFER_ASIGNADO TEXT,
        UNIDAD_ASIGNADA TEXT,
        FOREIGN KEY (EMP_ID) REFERENCES EMPRESAS(EMP_ID),
        FOREIGN KEY (CLI_ID) REFERENCES CLIENTES_LM(CLI_ID)
    )""")

    c.execute("""CREATE TABLE IF NOT EXISTS PEDIDO_HISTORIAL (
        HIS_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        PED_ID INTEGER NOT NULL,
        HIS_ESTADO TEXT NOT NULL,
        HIS_FECHA TEXT DEFAULT (datetime('now')),
        HIS_USUARIO TEXT,
        HIS_OBSERVACIONES TEXT,
        FOREIGN KEY (PED_ID) REFERENCES PEDIDOS(PED_ID)
    )""")

    # ========================================
    # TRACKING GPS
    # ========================================
    c.execute("""CREATE TABLE IF NOT EXISTS TRACKING (
        TRK_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        EMP_ID INTEGER NOT NULL,
        CHO_ID INTEGER,
        VEH_ID INTEGER,
        TRK_LATITUD REAL,
        TRK_LONGITUD REAL,
        TRK_VELOCIDAD REAL DEFAULT 0,
        TRK_RUMBO REAL DEFAULT 0,
        TRK_FECHA TEXT DEFAULT (datetime('now')),
        TRK_BATERIA REAL DEFAULT 100,
        FOREIGN KEY (EMP_ID) REFERENCES EMPRESAS(EMP_ID)
    )""")

    # ========================================
    # ZONAS DE COBERTURA
    # ========================================
    c.execute("""CREATE TABLE IF NOT EXISTS ZONAS (
        ZON_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        ZON_EMP_ID INTEGER NOT NULL,
        ZON_NOMBRE TEXT NOT NULL,
        ZON_DESCRIPCION TEXT,
        ZON_COLOR TEXT DEFAULT '#6366f1',
        ZON_RADIO_KM REAL DEFAULT 5.0,
        ZON_CENTRO_LAT REAL,
        ZON_CENTRO_LNG REAL,
        ZON_ACTIVO TEXT DEFAULT 'S',
        ZON_CREATED TEXT DEFAULT (datetime('now')),
        ZON_UPDATED TEXT DEFAULT (datetime('now')),
        FOREIGN KEY (ZON_EMP_ID) REFERENCES EMPRESAS(EMP_ID)
    )""")

    c.execute("""CREATE TABLE IF NOT EXISTS ZONA_TARIFAS (
        ZTA_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        ZTA_ZON_ID INTEGER NOT NULL,
        ZTA_EMP_ID INTEGER NOT NULL,
        ZTA_SERVICIO TEXT DEFAULT 'ESTANDAR',
        ZTA_MONTO_BASE REAL DEFAULT 0,
        ZTA_MONTO_POR_KG REAL DEFAULT 0,
        ZTA_MONTO_POR_KM REAL DEFAULT 0,
        ZTA_MONTO_POR_M3 REAL DEFAULT 0,
        ZTA_PESO_MIN_KG REAL DEFAULT 0.5,
        ZTA_PESO_MAX_KG REAL DEFAULT 30.0,
        ZTA_DISTANCIA_MAX_KM REAL DEFAULT 50.0,
        ZTA_MONTO_MINIMO REAL DEFAULT 35.0,
        ZTA_SEGURO_PCT REAL DEFAULT 0,
        ZTA_ACTIVO TEXT DEFAULT 'S',
        ZTA_CREATED TEXT DEFAULT (datetime('now')),
        FOREIGN KEY (ZTA_ZON_ID) REFERENCES ZONAS(ZON_ID),
        FOREIGN KEY (ZTA_EMP_ID) REFERENCES EMPRESAS(EMP_ID)
    )""")

    c.execute("CREATE INDEX IF NOT EXISTS IX_ZON_EMP ON ZONAS(ZON_EMP_ID)")
    c.execute("CREATE INDEX IF NOT EXISTS IX_ZTA_EMP ON ZONA_TARIFAS(ZTA_EMP_ID)")
    c.execute("CREATE INDEX IF NOT EXISTS IX_ZTA_ZON ON ZONA_TARIFAS(ZTA_ZON_ID)")

    # ========================================
    # CFDI / FACTURACION
    # ========================================
    c.execute("""CREATE TABLE IF NOT EXISTS CFDI_EMPRESA_FISCAL (
        FISC_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        EMP_ID INTEGER NOT NULL UNIQUE,
        FISC_RFC TEXT,
        FISC_RAZON_SOCIAL TEXT,
        FISC_REGIMEN_FISCAL TEXT,
        FISC_CODIGO_POSTAL TEXT,
        FISC_COLONIA TEXT,
        FISC_CALLE TEXT,
        FISC_NUMERO_EXTERIOR TEXT,
        FISC_MUNICIPIO TEXT,
        FISC_ESTADO TEXT,
        FISC_TELEFONO TEXT,
        FISC_EMAIL TEXT,
        FISC_TIPO_PERSONA TEXT DEFAULT 'M',
        FOREIGN KEY (EMP_ID) REFERENCES EMPRESAS(EMP_ID)
    )""")

    c.execute("""CREATE TABLE IF NOT EXISTS CFDI_FOLIOS (
        FOL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        EMP_ID INTEGER NOT NULL,
        FOL_SERIE TEXT NOT NULL,
        FOL_SIGUIENTE INTEGER DEFAULT 1,
        FOL_FINAL INTEGER DEFAULT 1000,
        FOL_ESTATUS TEXT DEFAULT 'ACTIVO',
        FOREIGN KEY (EMP_ID) REFERENCES EMPRESAS(EMP_ID)
    )""")

    c.execute("""CREATE TABLE IF NOT EXISTS CFDI_FACTURAS (
        FAC_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        EMP_ID INTEGER NOT NULL,
        FAC_UUID TEXT,
        FAC_SERIE TEXT,
        FAC_FOLIO TEXT,
        FAC_FECHA_EMISION TEXT DEFAULT (datetime('now')),
        FAC_FECHA_TIMBRADO TEXT,
        FAC_FORMA_PAGO TEXT DEFAULT '01',
        FAC_METODO_PAGO TEXT DEFAULT 'PUE',
        FAC_CONDICION_PAGO TEXT DEFAULT 'CONTADO',
        FAC_NUM_PARCIALIDADES INTEGER DEFAULT 1,
        FAC_SUBTOTAL REAL DEFAULT 0,
        FAC_DESCUENTO REAL DEFAULT 0,
        FAC_TOTAL_IVA REAL DEFAULT 0,
        FAC_TOTAL_ISR REAL DEFAULT 0,
        FAC_TOTAL_RETENCIONES REAL DEFAULT 0,
        FAC_TOTAL REAL DEFAULT 0,
        FAC_MONEDA TEXT DEFAULT 'MXN',
        FAC_TIPO_CAMBIO REAL DEFAULT 1,
        FAC_RECEPTOR_RFC TEXT,
        FAC_RECEPTOR_RAZON TEXT,
        FAC_RECEPTOR_REGIMEN TEXT DEFAULT '601',
        FAC_RECEPTOR_CP TEXT DEFAULT '00000',
        FAC_RECEPTOR_USO_CFDI TEXT DEFAULT 'G03',
        FAC_RECEPTOR_EMAIL TEXT,
        FAC_PED_ID INTEGER,
        FAC_RUT_ID INTEGER,
        FAC_XML_TIMBRADO TEXT,
        FAC_PDF_URL TEXT,
        FAC_ESTATUS TEXT DEFAULT 'PENDIENTE',
        FAC_MOTIVO_CANCELACION TEXT,
        FAC_UUID_SUSTITUCION TEXT,
        FAC_TIPO_DOCUMENTO TEXT DEFAULT 'INGRESO',
        FAC_NOTAS TEXT,
        FAC_FECHA_REGISTRO TEXT DEFAULT (datetime('now')),
        FOREIGN KEY (EMP_ID) REFERENCES EMPRESAS(EMP_ID),
        FOREIGN KEY (FAC_PED_ID) REFERENCES PEDIDOS(PED_ID)
    )""")

    c.execute("""CREATE TABLE IF NOT EXISTS CFDI_TIMBRADO_LOG (
        TIM_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        FAC_ID INTEGER NOT NULL,
        TIM_PAC TEXT,
        TIM_REQUEST TEXT,
        TIM_RESPONSE TEXT,
        TIM_CODIGO_RESPUESTA TEXT,
        TIM_MENSAJE TEXT,
        TIM_FECHA TEXT DEFAULT (datetime('now')),
        TIM_EXITOSO TEXT DEFAULT 'N',
        FOREIGN KEY (FAC_ID) REFERENCES CFDI_FACTURAS(FAC_ID)
    )""")

    c.execute("""CREATE TABLE IF NOT EXISTS CFDI_CONCEPTOS_CATALOGO (
        COC_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        EMP_ID INTEGER NOT NULL,
        COC_CLAVE_PROD_SERV TEXT,
        COC_DESCRIPCION TEXT,
        COC_CLAVE_UNIDAD TEXT,
        COC_UNIDAD TEXT,
        COC_PORCENTAJE_IVA REAL DEFAULT 16,
        COC_ESTATUS TEXT DEFAULT 'ACTIVO',
        FOREIGN KEY (EMP_ID) REFERENCES EMPRESAS(EMP_ID)
    )""")

    # ========================================
    # PAGOS
    # ========================================
    c.execute("""CREATE TABLE IF NOT EXISTS PAGOS_METODOS (
        PMT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        EMP_ID INTEGER NOT NULL,
        PMT_TIPO TEXT NOT NULL,
        PMT_NOMBRE TEXT,
        PMT_CONFIG TEXT,
        PMT_ACTIVO TEXT DEFAULT 'S',
        FOREIGN KEY (EMP_ID) REFERENCES EMPRESAS(EMP_ID)
    )""")

    c.execute("""CREATE TABLE IF NOT EXISTS PAGOS_TRANSACCIONES (
        TRP_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        EMP_ID INTEGER NOT NULL,
        PED_ID INTEGER,
        FAC_ID INTEGER,
        TRP_NUM_REFERENCIA TEXT,
        TRP_MONTO REAL DEFAULT 0,
        TRP_MONEDA TEXT DEFAULT 'MXN',
        TRP_METODO TEXT,
        TRP_ESTATUS TEXT DEFAULT 'PENDIENTE',
        TRP_FECHA_REGISTRO TEXT DEFAULT (datetime('now')),
        TRP_FECHA_CONCILIACION TEXT,
        TRP_CONCILIADO TEXT DEFAULT 'N',
        TRP_NOTAS TEXT,
        FOREIGN KEY (EMP_ID) REFERENCES EMPRESAS(EMP_ID)
    )""")

    # ========================================
    # AUDITORIA
    # ========================================
    c.execute("""CREATE TABLE IF NOT EXISTS AUDIT_LOG (
        AUD_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        EMP_ID INTEGER NOT NULL,
        AUD_USUARIO TEXT,
        AUD_ACCION TEXT,
        AUD_TABLA TEXT,
        AUD_REGISTRO_ID INTEGER,
        AUD_DETALLE TEXT,
        AUD_IP TEXT,
        AUD_FECHA TEXT DEFAULT (datetime('now')),
        FOREIGN KEY (EMP_ID) REFERENCES EMPRESAS(EMP_ID)
    )""")

    # ========================================
    # CLIENTE FINAL (Tracking para destinatario)
    # ========================================
    c.execute("""CREATE TABLE IF NOT EXISTS CLIENTE_FINAL (
        CLIF_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        EMP_ID INTEGER NOT NULL,
        PED_ID INTEGER NOT NULL,
        CLIF_NOMBRE TEXT,
        CLIF_TELEFONO TEXT,
        CLIF_EMAIL TEXT,
        CLIF_TOKEN_TRACKING TEXT UNIQUE,
        CLIF_NOTIF_SMS TEXT DEFAULT 'N',
        CLIF_NOTIF_WHATSAPP TEXT DEFAULT 'N',
        CLIF_NOTIF_EMAIL TEXT DEFAULT 'N',
        CLIF_FECHA_REGISTRO TEXT DEFAULT (datetime('now')),
        FOREIGN KEY (EMP_ID) REFERENCES EMPRESAS(EMP_ID),
        FOREIGN KEY (PED_ID) REFERENCES PEDIDOS(PED_ID)
    )""")

    # ========================================
    # SaaS BILLING
    # ========================================
    c.execute("""CREATE TABLE IF NOT EXISTS SAAS_PLANES (
        PLAN_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        PLAN_NOMBRE TEXT NOT NULL,
        PLAN_DESCRIPCION TEXT,
        PLAN_PRECIO_MENSUAL REAL DEFAULT 0,
        PLAN_PRECIO_ANUAL REAL DEFAULT 0,
        PLAN_MAX_CHOFERES INTEGER DEFAULT 5,
        PLAN_MAX_ENVIOS_MES INTEGER DEFAULT 100,
        PLAN_MAX_USUARIOS INTEGER DEFAULT 3,
        PLAN_MAX_SUCURSALES INTEGER DEFAULT 1,
        PLAN_FEATURES TEXT DEFAULT '{}',
        PLAN_ACTIVO TEXT DEFAULT 'S',
        PLAN_ORDEN INTEGER DEFAULT 0
    )""")

    c.execute("""CREATE TABLE IF NOT EXISTS SAAS_SUSCRIPCIONES (
        SUS_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        EMP_ID INTEGER NOT NULL,
        PLAN_ID INTEGER NOT NULL,
        SUS_ESTADO TEXT DEFAULT 'TRIAL',
        SUS_FECHA_INICIO TEXT,
        SUS_FECHA_FIN TEXT,
        SUS_FECHA_PROXIMO_COBRO TEXT,
        SUS_FACTURACION_CICLO TEXT DEFAULT 'MENSUAL',
        SUS_METODO_PAGO TEXT,
        SUS_MP_CUSTOMER_ID TEXT,
        SUS_MP_SUBSCRIPTION_ID TEXT,
        SUS_STRIPE_CUSTOMER_ID TEXT,
        SUS_STRIPE_SUBSCRIPTION_ID TEXT,
        SUS_TOTAL_COBRADO REAL DEFAULT 0,
        SUS_FECHA_REGISTRO TEXT DEFAULT (datetime('now')),
        SUS_NOTAS TEXT,
        FOREIGN KEY (EMP_ID) REFERENCES EMPRESAS(EMP_ID),
        FOREIGN KEY (PLAN_ID) REFERENCES SAAS_PLANES(PLAN_ID)
    )""")

    c.execute("""CREATE TABLE IF NOT EXISTS SAAS_COBROS (
        COB_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        SUS_ID INTEGER NOT NULL,
        EMP_ID INTEGER NOT NULL,
        COB_MONTO REAL DEFAULT 0,
        COB_MONEDA TEXT DEFAULT 'MXN',
        COB_CONCEPTO TEXT,
        COB_ESTATUS TEXT DEFAULT 'PENDIENTE',
        COB_METODO_PAGO TEXT,
        COB_REFERENCIA_PAGO TEXT,
        COB_FECHA_COBRO TEXT DEFAULT (datetime('now')),
        COB_FECHA_APLICADO TEXT,
        COB_FACTURA_ID INTEGER,
        COB_JSON_RESPUESTA TEXT,
        COB_NOTAS TEXT,
        FOREIGN KEY (SUS_ID) REFERENCES SAAS_SUSCRIPCIONES(SUS_ID),
        FOREIGN KEY (EMP_ID) REFERENCES EMPRESAS(EMP_ID)
    )""")

    c.execute("""CREATE TABLE IF NOT EXISTS SAAS_USO_RECURSOS (
        USR_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        EMP_ID INTEGER NOT NULL,
        USR_FECHA TEXT DEFAULT (date('now')),
        USR_PEDIDOS_CREADOS INTEGER DEFAULT 0,
        USR_PEDIDOS_ENTREGADOS INTEGER DEFAULT 0,
        USR_ENVIOS_SMS INTEGER DEFAULT 0,
        USR_ENVIOS_EMAIL INTEGER DEFAULT 0,
        USR_API_CALLS INTEGER DEFAULT 0,
        FOREIGN KEY (EMP_ID) REFERENCES EMPRESAS(EMP_ID)
    )""")

    # ========================================
    # NOTIFICACIONES
    # ========================================
    c.execute("""CREATE TABLE IF NOT EXISTS NOTIF_PUSH (
        NPUSH_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        EMP_ID INTEGER NOT NULL,
        USR_ID INTEGER,
        CHO_ID INTEGER,
        NPUSH_TIPO TEXT,
        NPUSH_TITULO TEXT,
        NPUSH_CUERPO TEXT,
        NPUSH_DATA TEXT DEFAULT '{}',
        NPUSH_ENVIADO TEXT DEFAULT 'N',
        NPUSH_LEIDO TEXT DEFAULT 'N',
        NPUSH_FECHA_REGISTRO TEXT DEFAULT (datetime('now')),
        FOREIGN KEY (EMP_ID) REFERENCES EMPRESAS(EMP_ID)
    )""")

    c.execute("""CREATE TABLE IF NOT EXISTS NOTIF_DISPOSITIVOS (
        DISP_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        EMP_ID INTEGER NOT NULL,
        USR_ID INTEGER,
        CHO_ID INTEGER,
        DISP_TOKEN TEXT,
        DISP_PLATAFORMA TEXT DEFAULT 'WEB',
        DISP_ACTIVO TEXT DEFAULT 'S',
        DISP_FECHA_REGISTRO TEXT DEFAULT (datetime('now')),
        FOREIGN KEY (EMP_ID) REFERENCES EMPRESAS(EMP_ID)
    )""")

    # ========================================
    # EMAIL / SMS
    # ========================================
    c.execute("""CREATE TABLE IF NOT EXISTS EMAIL_ENVIADOS (
        EMAIL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        EMP_ID INTEGER NOT NULL,
        PED_ID INTEGER,
        FAC_ID INTEGER,
        EMAIL_DESTINATARIO TEXT,
        EMAIL_ASUNTO TEXT,
        EMAIL_TIPO TEXT,
        EMAIL_BODY_HTML TEXT,
        EMAIL_ENVIADO TEXT DEFAULT 'N',
        EMAIL_FECHA_REGISTRO TEXT DEFAULT (datetime('now')),
        EMAIL_FECHA_ENVIO TEXT,
        EMAIL_ERROR TEXT,
        FOREIGN KEY (EMP_ID) REFERENCES EMPRESAS(EMP_ID)
    )""")

    c.execute("""CREATE TABLE IF NOT EXISTS SMS_ENVIADOS (
        SMS_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        EMP_ID INTEGER NOT NULL,
        PED_ID INTEGER,
        SMS_TELEFONO TEXT,
        SMS_MENSAJE TEXT,
        SMS_PLATAFORMA TEXT DEFAULT 'SMS',
        SMS_ENVIADO TEXT DEFAULT 'N',
        SMS_COSTO REAL DEFAULT 0,
        SMS_FECHA_REGISTRO TEXT DEFAULT (datetime('now')),
        SMS_FECHA_ENVIO TEXT,
        SMS_ERROR TEXT,
        FOREIGN KEY (EMP_ID) REFERENCES EMPRESAS(EMP_ID)
    )""")

    # ========================================
    # REPORTES
    # ========================================
    c.execute("""CREATE TABLE IF NOT EXISTS REPORTES_GENERADOS (
        RPT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        EMP_ID INTEGER NOT NULL,
        RPT_TIPO TEXT NOT NULL,
        RPT_NOMBRE TEXT,
        RPT_PARAMETROS TEXT DEFAULT '{}',
        RPT_RUTA_ARCHIVO TEXT,
        RPT_GENERADO_POR TEXT,
        RPT_FECHA_GENERACION TEXT DEFAULT (datetime('now')),
        FOREIGN KEY (EMP_ID) REFERENCES EMPRESAS(EMP_ID)
    )""")

    # ========================================
    # ENTREGAS
    # ========================================
    c.execute("""CREATE TABLE IF NOT EXISTS ENTREGAS (
        ENT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        EMP_ID INTEGER NOT NULL,
        PED_ID INTEGER,
        CHO_ID INTEGER,
        VEH_ID INTEGER,
        ENT_ESTADO TEXT DEFAULT 'PENDIENTE',
        ENT_FECHA_SALIDA TEXT,
        ENT_FECHA_LLEGADA TEXT,
        ENT_EVIDENCIA TEXT,
        ENT_FIRMA TEXT,
        ENT_LATITUD REAL,
        ENT_LONGITUD REAL,
        ENT_NOTAS TEXT,
        FOREIGN KEY (EMP_ID) REFERENCES EMPRESAS(EMP_ID)
    )""")

    # ========================================
    # INCIDENCIAS
    # ========================================
    c.execute("""CREATE TABLE IF NOT EXISTS INCIDENCIAS (
        INC_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        EMP_ID INTEGER NOT NULL,
        PED_ID INTEGER,
        CHO_ID INTEGER,
        INC_TIPO TEXT,
        INC_DESCRIPCION TEXT,
        INC_FECHA TEXT DEFAULT (datetime('now')),
        INC_RESUELTA TEXT DEFAULT 'N',
        INC_FECHA_RESOLUCION TEXT,
        INC_USUARIO_REPORTA TEXT,
        INC_USUARIO_RESUELVE TEXT,
        FOREIGN KEY (EMP_ID) REFERENCES EMPRESAS(EMP_ID)
    )""")

    c.execute("""CREATE TABLE IF NOT EXISTS KPI_DIARIO (
        KPI_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        EMP_ID INTEGER NOT NULL,
        KPI_FECHA TEXT DEFAULT (date('now')),
        KPI_PEDIDOS_CREADOS INTEGER DEFAULT 0,
        KPI_PEDIDOS_ENTREGADOS INTEGER DEFAULT 0,
        KPI_PEDIDOS_CANCELADOS INTEGER DEFAULT 0,
        KPI_INGRESOS REAL DEFAULT 0,
        KPI_COSTOS REAL DEFAULT 0,
        KPI_UTILIDAD REAL DEFAULT 0,
        KPI_ENTREGAS_PUNTUALES INTEGER DEFAULT 0,
        KPI_ENTREGAS_TARDIAS INTEGER DEFAULT 0,
        KPI_INCIDENCIAS INTEGER DEFAULT 0,
        KPI_PROMEDIO_TIEMPO_ENTREGA REAL DEFAULT 0,
        FOREIGN KEY (EMP_ID) REFERENCES EMPRESAS(EMP_ID)
    )""")

    # ========================================
    # VISTAS (SQLite views)
    # ========================================

    # Dashboard resumen
    c.execute("DROP VIEW IF EXISTS V_DASHBOARD_RESUMEN")
    c.execute("""CREATE VIEW V_DASHBOARD_RESUMEN AS
        SELECT e.EMP_ID, e.EMP_NOMBRE,
            (SELECT COUNT(*) FROM PEDIDOS p WHERE p.EMP_ID = e.EMP_ID) as TOTAL_PEDIDOS,
            (SELECT COUNT(*) FROM PEDIDOS p WHERE p.EMP_ID = e.EMP_ID AND p.PED_ESTADO = 'PENDIENTE') as PEDIDOS_PENDIENTES,
            (SELECT COUNT(*) FROM PEDIDOS p WHERE p.EMP_ID = e.EMP_ID AND p.PED_ESTADO = 'EN_RUTA') as PEDIDOS_EN_RUTA,
            (SELECT COUNT(*) FROM PEDIDOS p WHERE p.EMP_ID = e.EMP_ID AND p.PED_ESTADO = 'ENTREGADO') as PEDIDOS_ENTREGADOS,
            (SELECT COUNT(*) FROM CHOFERES c WHERE c.EMP_ID = e.EMP_ID AND c.CHO_ESTATUS = 'ACTIVO') as CHOFERES_ACTIVOS,
            (SELECT COUNT(*) FROM VEHICULOS v WHERE v.EMP_ID = e.EMP_ID AND v.VEH_ESTATUS = 'DISPONIBLE') as VEHICULOS_DISPONIBLES,
            (SELECT COUNT(*) FROM CLIENTES_LM cl WHERE cl.EMP_ID = e.EMP_ID) as TOTAL_CLIENTES,
            (SELECT COALESCE(SUM(p2.PED_COSTO_TOTAL), 0) FROM PEDIDOS p2 WHERE p2.EMP_ID = e.EMP_ID AND p2.PED_ESTADO = 'ENTREGADO') as INGRESOS_MES
        FROM EMPRESAS e
    """)

    # Pedidos completo
    c.execute("DROP VIEW IF EXISTS V_PEDIDOS_COMPLETO")
    c.execute("""CREATE VIEW V_PEDIDOS_COMPLETO AS
        SELECT p.*, e.EMP_NOMBRE,
            (SELECT COUNT(*) FROM PEDIDO_HISTORIAL h WHERE h.PED_ID = p.PED_ID) as TOTAL_MOVIMIENTOS
        FROM PEDIDOS p
        LEFT JOIN EMPRESAS e ON p.EMP_ID = e.EMP_ID
    """)

    # Rendimiento choferes
    c.execute("DROP VIEW IF EXISTS V_RENDIMIENTO_CHOFERES")
    c.execute("""CREATE VIEW V_RENDIMIENTO_CHOFERES AS
        SELECT c.CHO_ID, c.EMP_ID, c.CHO_NOMBRE, c.CHO_APELLIDO,
            (SELECT COUNT(*) FROM PEDIDOS p WHERE p.CHO_ID = c.CHO_ID AND p.PED_ESTADO = 'ENTREGADO') as ENTREGAS_REALIZADAS,
            (SELECT COUNT(*) FROM PEDIDOS p WHERE p.CHO_ID = c.CHO_ID) as TOTAL_ASIGNACIONES,
            CASE WHEN (SELECT COUNT(*) FROM PEDIDOS p WHERE p.CHO_ID = c.CHO_ID) > 0
                THEN ROUND(CAST((SELECT COUNT(*) FROM PEDIDOS p WHERE p.CHO_ID = c.CHO_ID AND p.PED_ESTADO = 'ENTREGADO') AS REAL) * 100.0 / (SELECT COUNT(*) FROM PEDIDOS p WHERE p.CHO_ID = c.CHO_ID), 1)
                ELSE 0 END as TASA_EXITO,
            (SELECT AVG(CASE WHEN p.PED_FECHA_ENTREGA_REAL IS NOT NULL AND p.PED_FECHA_RECOLECTA IS NOT NULL
                THEN (julianday(p.PED_FECHA_ENTREGA_REAL) - julianday(p.PED_FECHA_RECOLECTA)) * 24
                ELSE NULL END)
                FROM PEDIDOS p WHERE p.CHO_ID = c.CHO_ID AND p.PED_ESTADO = 'ENTREGADO') as PROMEDIO_HORAS,
            (SELECT COALESCE(SUM(t.TRK_VELOCIDAD), 0) / CASE WHEN COUNT(t.TRK_ID) > 0 THEN COUNT(t.TRK_ID) ELSE 1 END
                FROM TRACKING t WHERE t.CHO_ID = c.CHO_ID) as VELOCIDAD_PROMEDIO
        FROM CHOFERES c
    """)

    # Estado flota
    c.execute("DROP VIEW IF EXISTS V_ESTADO_FLOTA")
    c.execute("""CREATE VIEW V_ESTADO_FLOTA AS
        SELECT v.*, c.CHO_NOMBRE, c.CHO_APELLIDO,
            (SELECT COUNT(*) FROM PEDIDOS p WHERE p.VEH_ID = v.VEH_ID AND p.PED_ESTADO = 'EN_RUTA') as ENVIOS_ACTIVOS,
            (SELECT t.TRK_LATITUD FROM TRACKING t WHERE t.VEH_ID = v.VEH_ID ORDER BY t.TRK_FECHA DESC LIMIT 1) as ULT_LAT,
            (SELECT t.TRK_LONGITUD FROM TRACKING t WHERE t.VEH_ID = v.VEH_ID ORDER BY t.TRK_FECHA DESC LIMIT 1) as ULT_LNG,
            (SELECT t.TRK_VELOCIDAD FROM TRACKING t WHERE t.VEH_ID = v.VEH_ID ORDER BY t.TRK_FECHA DESC LIMIT 1) as ULT_VELOCIDAD
        FROM VEHICULOS v
        LEFT JOIN CHOFERES c ON v.VEH_ID = c.CHO_ID
    """)

    # Costos ruta
    c.execute("DROP VIEW IF EXISTS V_COSTOS_RUTA")
    c.execute("""CREATE VIEW V_COSTOS_RUTA AS
        SELECT r.*, e.EMP_NOMBRE
        FROM PEDIDOS r
        LEFT JOIN EMPRESAS e ON r.EMP_ID = e.EMP_ID
        WHERE r.PED_ESTADO IN ('EN_RUTA', 'ENTREGADO')
    """)

    # Top clientes
    c.execute("DROP VIEW IF EXISTS V_TOP_CLIENTES")
    c.execute("""CREATE VIEW V_TOP_CLIENTES AS
        SELECT cl.CLI_ID, cl.EMP_ID, cl.CLI_RAZON_SOCIAL, cl.CLI_TELEFONO, cl.CLI_EMAIL,
            (SELECT COUNT(*) FROM PEDIDOS p WHERE p.CLI_ID = cl.CLI_ID) as TOTAL_PEDIDOS,
            (SELECT COALESCE(SUM(p.PED_COSTO_TOTAL), 0) FROM PEDIDOS p WHERE p.CLI_ID = cl.CLI_ID) as TOTAL_GASTADO
        FROM CLIENTES_LM cl
    """)

    # KPI consolidado
    c.execute("DROP VIEW IF EXISTS V_KPI_CONSOLIDADO")
    c.execute("""CREATE VIEW V_KPI_CONSOLIDADO AS
        SELECT e.EMP_ID,
            (SELECT COUNT(*) FROM PEDIDOS p WHERE p.EMP_ID = e.EMP_ID AND p.PED_FECHA_PEDIDO >= date('now', '-30 days')) as PEDIDOS_MES,
            (SELECT COALESCE(SUM(p.PED_COSTO_TOTAL), 0) FROM PEDIDOS p WHERE p.EMP_ID = e.EMP_ID AND p.PED_FECHA_PEDIDO >= date('now', '-30 days')) as INGRESOS_MES,
            (SELECT COUNT(*) FROM PEDIDOS p WHERE p.EMP_ID = e.EMP_ID AND p.PED_ESTADO = 'ENTREGADO' AND p.PED_FECHA_PEDIDO >= date('now', '-30 days')) as ENTREGAS_MES,
            (SELECT COUNT(*) FROM INCIDENCIAS i WHERE i.EMP_ID = e.EMP_ID AND i.INC_FECHA >= date('now', '-30 days')) as INCIDENCIAS_MES
        FROM EMPRESAS e
    """)

    # Incidencias resumen
    c.execute("DROP VIEW IF EXISTS V_INCIDENCIAS_RESUMEN")
    c.execute("""CREATE VIEW V_INCIDENCIAS_RESUMEN AS
        SELECT i.EMP_ID,
            COUNT(*) as TOTAL,
            SUM(CASE WHEN i.INC_RESUELTA = 'S' THEN 1 ELSE 0 END) as RESUELTAS,
            SUM(CASE WHEN i.INC_RESUELTA = 'N' THEN 1 ELSE 0 END) as PENDIENTES
        FROM INCIDENCIAS i
        GROUP BY i.EMP_ID
    """)

    conn.commit()
    conn.close()
    print(f"Database created at {DB_PATH}")


if __name__ == '__main__':
    init_db()
